/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-10-15 02:38:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내정보 조회하기</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	#hobby-wrap{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    justify-content: center;\r\n");
      out.write("	    flex-direction: row;\r\n");
      out.write("	    flex-wrap: nowrap;\r\n");
      out.write("	    align-items: baseline;\r\n");
      out.write("	}\r\n");
      out.write("	input[type=checkbox]{\r\n");
      out.write("		margin-left : 50px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"width : 80%; margin : auto; padding : 50px;\">\r\n");
      out.write("		<form action=\"update.me\" name=\"signup\" id=\"signUpForm\" method=\"post\"\r\n");
      out.write("						style=\"margin-bottom: 0;\">\r\n");
      out.write("			<table\r\n");
      out.write("				style=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p><strong>아이디는 변경할 수 없습니다.</strong>&nbsp;&nbsp;&nbsp;<span id=\"idChk\"></span></p>\r\n");
      out.write("					</td>							\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"text\" name=\"userId\" id=\"user_id\"\r\n");
      out.write("						class=\"form-control tooltipstered\" maxlength=\"14\"\r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("						</td>\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p><strong>이름을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"nameChk\"></span></p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"text\" name=\"userName\" id=\"user_name\"\r\n");
      out.write("						class=\"form-control tooltipstered\" maxlength=\"6\"\r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"한글로 최대 6자\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: left\">\r\n");
      out.write("						<p><strong>이메일을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"emailChk\"></span></p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"email\" name=\"email\" id=\"user_email\"\r\n");
      out.write("						class=\"form-control tooltipstered\" \r\n");
      out.write("						required=\"required\" aria-required=\"true\"\r\n");
      out.write("						style=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("						placeholder=\"ex) kh@kh.com\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("	\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("						<p><strong>원하시는 서비스를 선택해주세요.</strong></p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("						type=\"submit\" value=\"정보수정\" \r\n");
      out.write("						class=\"btn form-control tooltipstered\" id=\"signup-btn\"\r\n");
      out.write("						style=\"background-color: #52b1ff; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("						type=\"button\" value=\"비밀번호수정\" \r\n");
      out.write("						class=\"btn form-control tooltipstered\" id=\"signup-btn\"\r\n");
      out.write("						style=\"background-color: #52ffe9; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\"\r\n");
      out.write("						data-toggle=\"modal\" data-target=\"#updatePwd\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("						type=\"button\" value=\"회원탈퇴\" \r\n");
      out.write("						class=\"btn form-control tooltipstered\" id=\"signup-btn\"\r\n");
      out.write("						style=\"background-color: #ff5352; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\"\r\n");
      out.write("						data-toggle=\"modal\" data-target=\"#deleteForm\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	 	<!-- 회원 탈퇴 모달 -->\r\n");
      out.write("	<div class=\"modal\" id=\"deleteForm\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h4 class=\"modal-title\" style=\"color:red;\">회원 탈퇴</h4>\r\n");
      out.write("	        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <form action=\"delete.me\" method=\"post\">\r\n");
      out.write("	        	<input type=\"hidden\" name=\"userNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.userNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			  <div class=\"form-group\">\r\n");
      out.write("			    <label for=\"userPwd\" style=\"font-size:12px; color:red\">탈퇴를 원하신다면 비밀번호를 입력해주세요.</label>\r\n");
      out.write("			    <input type=\"password\" name=\"userPwd\" class=\"form-control\" placeholder=\"비밀번호를 입력해주세요.\" id=\"deletePwd\" required>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  \r\n");
      out.write("			  <button type=\"submit\" class=\"btn btn-danger\" onclick=\"return deleteMember();\">회원탈퇴</button>\r\n");
      out.write("			  \r\n");
      out.write("			  <script>\r\n");
      out.write("			  	function deleteMember(){\r\n");
      out.write("			  		\r\n");
      out.write("			  		const value = prompt('탈퇴를 원하신다면 \"어쩌고저쩌고\"를 정확히 입력해주세요.');\r\n");
      out.write("			  		\r\n");
      out.write("			  		if(value === '어쩌고저쩌고'){\r\n");
      out.write("						return true;	  			\r\n");
      out.write("			  		}\r\n");
      out.write("			  		else{\r\n");
      out.write("			  			return false;\r\n");
      out.write("			  		}\r\n");
      out.write("			  		\r\n");
      out.write("			  	}\r\n");
      out.write("			  </script>\r\n");
      out.write("			</form>\r\n");
      out.write("	      </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 비밀번호 변경 모달 -->\r\n");
      out.write("	<div class=\"modal\" id=\"updatePwd\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("	        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <form action=\"updatePwd.me\" method=\"post\">\r\n");
      out.write("	        \r\n");
      out.write("			  <div class=\"form-group\">\r\n");
      out.write("			    <label for=\"userPwd\">현재 비밀번호 :</label>\r\n");
      out.write("			    <input type=\"password\" name=\"userPwd\" class=\"form-control\" placeholder=\"비밀번호를 입력해주세요.\" id=\"userPwd\" required>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  \r\n");
      out.write("			  <div class=\"form-group\">\r\n");
      out.write("			    <label for=\"changePwd\">변경할 비밀번호 :</label>\r\n");
      out.write("			    <input type=\"password\" name=\"changePwd\" class=\"form-control\" placeholder=\"변경할 비밀번호를 입력해주세요.\" id=\"changePwd\" required>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  \r\n");
      out.write("			  <div class=\"form-group\">\r\n");
      out.write("			    <label for=\"checkPwd\">변경할 비밀번호 확인 :</label>\r\n");
      out.write("			    <input type=\"password\" class=\"form-control\" placeholder=\"다시 한 번 입력해주세요.\" id=\"checkPwd\" required>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  \r\n");
      out.write("			  <button type=\"submit\" class=\"btn btn-secondary\" onclick=\"return validatePwd();\">비밀번호 변경</button>\r\n");
      out.write("			  \r\n");
      out.write("			  <script>\r\n");
      out.write("			  	function validatePwd(){\r\n");
      out.write("			  		\r\n");
      out.write("			  		if($('#changePwd').val() != $('#checkPwd').val()){\r\n");
      out.write("			  			alert('비밀번호를 동일하게 입력해주세요!');\r\n");
      out.write("			  			$('#checkPwd').focus().val('');\r\n");
      out.write("			  			return false;\r\n");
      out.write("			  		}\r\n");
      out.write("			  		\r\n");
      out.write("			  		return true;\r\n");
      out.write("			  	}\r\n");
      out.write("			  </script>\r\n");
      out.write("			</form>\r\n");
      out.write("	      </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
